- name: mount piwigo efs
  mount:
    name: "{{efs_mount}}"
    src: "{{ansible_ec2_placement_availability_zone}}.{{efs_id}}.efs.{{ansible_ec2_placement_region}}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    state: mounted

- name: create data directory
  file:
    path: "{{ efs_folder }}/_data"
    state: directory
    mode: 0777


- name: create galleries directory
  file:
    path: "{{ efs_folder }}/piwigo/galleries"
    state: directory
    mode: 0777

- name: create local directory
  file:
    path: "{{ efs_folder }}/piwigo/local/config"
    state: directory
    mode: 0644
    owner: ec2-user
    group: ec2-user

- name: create plugins directory
  file:
    path: "{{ efs_folder }}/piwigo/plugins"
    state: directory
    mode: 0777

- name: create upload directory
  file:
    path: "{{ efs_folder }}/piwigo/upload"
    state: directory
    mode: 0777

- name: create database config
  template:
    src: database.j2.php
    dest: "{{ efs_folder }}/piwigo/local/config/database.inc.php"
    mode: 0644
    owner: ec2-user
    group: ec2-user