- name: mount piwigo efs
  mount:
    name: "{{efs_mount}}"
    src: "{{ansible_ec2_placement_availability_zone}}.{{efs_id}}.efs.{{ansible_ec2_placement_region}}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    state: mounted

- name: create data directory
  file:
    path: "{{ efs_folder }}"
    state: directory